-- Таблица категорий событий
CREATE TABLE IF NOT EXISTS categories (
                                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          name VARCHAR(50) NOT NULL UNIQUE,
                                          created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Таблица пользователей (инициаторов событий)
CREATE TABLE IF NOT EXISTS users (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     name VARCHAR(250) NOT NULL,
                                     email VARCHAR(254) NOT NULL UNIQUE,
                                     created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Таблица событий
CREATE TABLE IF NOT EXISTS events (
                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      annotation VARCHAR(2000) NOT NULL,
                                      category_id BIGINT NOT NULL,
                                      confirmed_requests INTEGER DEFAULT 0,
                                      created_on TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                                      description VARCHAR(7000),
                                      event_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                      initiator_id BIGINT NOT NULL,
                                      lat FLOAT,
                                      lon FLOAT,
                                      paid BOOLEAN DEFAULT FALSE,
                                      participant_limit INTEGER DEFAULT 0,
                                      published_on TIMESTAMP WITHOUT TIME ZONE,
                                      request_moderation BOOLEAN DEFAULT TRUE,
                                      state VARCHAR(20) DEFAULT 'PENDING',
                                      title VARCHAR(120) NOT NULL,

    -- Внешние ключи
                                      FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE RESTRICT,
                                      FOREIGN KEY (initiator_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Таблица заявок на участие в событиях
CREATE TABLE IF NOT EXISTS requests (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        created TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                                        event_id BIGINT NOT NULL,
                                        requester_id BIGINT NOT NULL,
                                        status VARCHAR(20) DEFAULT 'PENDING',

    -- Внешние ключи
                                        FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE,
                                        FOREIGN KEY (requester_id) REFERENCES users(id) ON DELETE CASCADE,

    -- Уникальный индекс для предотвращения дублирования заявок
                                        UNIQUE (event_id, requester_id)
);

-- Таблица подборок событий
CREATE TABLE IF NOT EXISTS compilations (
                                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            pinned BOOLEAN DEFAULT FALSE NOT NULL,
                                            title VARCHAR(50) NOT NULL,
                                            created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Связующая таблица для связи подборок и событий (многие-ко-многим)
CREATE TABLE IF NOT EXISTS compilation_events (
                                                  compilation_id BIGINT NOT NULL,
                                                  event_id BIGINT NOT NULL,

    -- Внешние ключи
                                                  FOREIGN KEY (compilation_id) REFERENCES compilations(id) ON DELETE CASCADE,
                                                  FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE,

    -- Составной первичный ключ
                                                  PRIMARY KEY (compilation_id, event_id)
);

-- Создаем индексы для оптимизации запросов
CREATE INDEX IF NOT EXISTS idx_events_category ON events(category_id);
CREATE INDEX IF NOT EXISTS idx_events_initiator ON events(initiator_id);
CREATE INDEX IF NOT EXISTS idx_events_state ON events(state);
CREATE INDEX IF NOT EXISTS idx_events_event_date ON events(event_date);
CREATE INDEX IF NOT EXISTS idx_events_published ON events(published_on);

CREATE INDEX IF NOT EXISTS idx_requests_event ON requests(event_id);
CREATE INDEX IF NOT EXISTS idx_requests_requester ON requests(requester_id);
CREATE INDEX IF NOT EXISTS idx_requests_status ON requests(status);

CREATE INDEX IF NOT EXISTS idx_compilation_events_event ON compilation_events(event_id);
CREATE INDEX IF NOT EXISTS idx_compilation_events_compilation ON compilation_events(compilation_id);

-- Индекс для поиска по тексту в событиях (для публичного поиска)
CREATE INDEX IF NOT EXISTS idx_events_annotation ON events(annotation);
CREATE INDEX IF NOT EXISTS idx_events_description ON events(description);